### ISSUE TITLE
Make user avatar shine toggle-able

### ISSUE THREAD

**Issue by Saltssaumure** [Saltssaumure/xp-discord-theme#22]
Common request from users on support server asking for an option to remove user avatar shine.

Current solution to add this in Custom/Quick CSS:
```css
.wrapper_edb6e0::before {
    display: none;
}
```
