### ISSUE TITLE
serverbar huge grey bar beneath

### ISSUE THREAD

**Issue by Mass1milian0** [Saltssaumure/xp-discord-theme#28]
there is this gray bar, i thought it was the discover server button, so i removed it, but that wasn't it

![image](https://github.com/user-attachments/assets/5a4a02da-10d1-4a60-8d7b-031bbcf99030)

**Comment by Mass1milian0** [comment]
upon further inspection, i noticed that by disabling flex-direction: column; the issue gets fixed

![image](https://github.com/user-attachments/assets/aeb90300-79a0-42ac-9d1c-e4b0da614b26)
![image](https://github.com/user-attachments/assets/cad34f9d-1c8b-4c60-b104-af438c88f947)

however i disabled it for the class .itemsContainer_fe3ef which seems like an instanced class, if removed for the general class, i have no idea what implications it may have

**Comment by devgocri** [comment]
I have the same issue, but removing flex-direction: column only makes everything appear to move to the left:

<img width="611" alt="image" src="https://github.com/user-attachments/assets/b42b0f2c-11a0-4ac6-a2b4-d950307aa1f8">

**Comment by Mass1milian0** [comment]
it's wierd, but, you are running a macos, which may interpret the css rules differently, however, the developer of this theme doesn't seem active anymore, this may be abandoned @devgocri

**Comment by TReKiE** [comment]
Changing flex-direction didn't work for me either.

After some experimentation over the past week, this is what I ended up adding into Vencord's QuickCSS to fix the theme for me:
```css
#app-mount > div.appAsidePanelWrapper_bd26cc > div.notAppAsidePanel_bd26cc > div.app_bd26cc > div > div.layers_d4b6c5.layers_a01fb1 > div > div > nav > ul
{
    background: linear-gradient(to left, var(--xp-window-color-1), var(--xp-window-color-1) 12%, var(--xp-window-color-2));
    box-shadow: inset 0 0 3px 2px var(--xp-window-color-1),inset -2px 0 2px 1px rgba(255,255,255,.7);
}

.footer_d71945
{
    background: unset;
}

.unreadMentionsIndicatorTop_fea3ef, .unreadMentionsIndicatorBottom_fea3ef {
    visibility: hidden;
}

.guilds_a4d4d9 .scroller_fea3ef {
    background: unset;
    box-shadow: unset;
}
```

**Comment by TReKiE** [comment]
New version for the latest changes:

```css
#app-mount > div.appAsidePanelWrapper_a3002d > div.notAppAsidePanel_a3002d > div.app_a3002d > div > div.layers__960e4.layers__160d8 > div > div > nav > ul,
div:nth-child(2) > nav > ul
{
    background: linear-gradient(to left, var(--xp-window-color-1), var(--xp-window-color-1) 12%, var(--xp-window-color-2));
    box-shadow: inset 0 0 3px 2px var(--xp-window-color-1),inset -2px 0 2px 1px rgba(255,255,255,.7);
}

.footer__214dc, .theme-light .content__37e49, .theme-dark .content__37e49
{
    background: unset;
}

.unreadMentionsIndicatorTop_ef3116, .unreadMentionsIndicatorBottom_ef3116 {
    visibility: hidden;
}

.guilds_c48ade .scroller_ef3116 {
    background: unset;
    box-shadow: unset;
}

.theme-light .title_b6c092 {
    color: white;
}

```
